word:
  delay: ...
  description:
    en_us: ...
  energy: ...
  kind: ...
    - constant.float
    - constant.integer
    - constant.integer.boolean
    - constant.rotation
    - constant.string
    - constant.vector
    - control.conditional
    - control.flow
    - control.loop
    - event
    - function.builtin
    - keyword
    - state
    - storage.type
  name: ...
  params:
    - name: ...
      type: ...
    - ...
  related:
    constants: ...
    events: ...
    functions: ...
  snippets:
    - ...
  status: ...
  type: ...
  usage:
    - ...
  value: ...
  version: ...

completion:
  - label: string
  - kind?: number
    - 1: Text
    - 2: Method
    - 3: Function
    - 4: Constructor
    - 5: Field
    - 6: Variable
    - 7: Class
    - 8: Interface
    - 9: Module
    - 10: Property
    - 11: Unit
    - 12: Value
    - 13: Enum
    - 14: Keyword
    - 15: Snippet
    - 16: Color
    - 17: File
    - 18: Reference
  - detail?: string
  - documentation?: string
  - sortText?: string
  - filterText?: string
  - insertText?: string

symbolInformation:
  - name: string
  - kind: number
    - 1: File
    - 2: Module
    - 3: Namespace
    - 4: Package
    - 5: Class
    - 6: Method
    - 7: Property
    - 8: Field
    - 9: Constructor
    - 10: Enum
    - 11: Interface
    - 12: Function
    - 13: Variable
    - 14: Constant
    - 15: String
    - 16: Number
    - 17: Boolean
    - 18: Array
  - location: Location
  - containerName: string
